### PR TITLE
msgpack-lite: fix BigInteger pack / unpack

### LINKED ISSUE #27: MsgPackLite broken pack for ulongs higher than Long.MAX_VALUE
It is possible to unpack ulong bigger than Long.MAX_VALUE correctly as BigInteger. But it is not possible to pack it correctly - it becomes unsigned.

```
	public static void main(String[] args) throws IOException {
		byte[] pack = bytesInQuestion();
		// correct unpacking
		BigInteger unpackValue = (BigInteger) MsgPackLite.INSTANCE.unpack(new ByteArrayInputStream(pack));
		// let's pack it back again
		ByteArrayOutputStream out = new ByteArrayOutputStream();
		MsgPackLite.INSTANCE.pack(unpackValue, out);
		byte[] repack = out.toByteArray();

		System.out.println(Arrays.equals(pack, repack));
		System.out.println(Arrays.toString(pack));
		System.out.println(Arrays.toString(repack));
		//false
		//[-49, -128, 0, 0, 0, 127, -1, -1, -2]
		//[-50, 127, -1, -1, -2]
	}

	private static byte[] bytesInQuestion() throws IOException {
		ByteArrayOutputStream out = new ByteArrayOutputStream();
		DataOutputStream dataStream = new DataOutputStream(out);
		try {
			dataStream.write(MsgPackLite.INSTANCE.MP_UINT64);
			dataStream.writeLong(Long.MAX_VALUE + Integer.MAX_VALUE);
			return out.toByteArray();
		} finally {
			dataStream.close();
		}
	}
```

### PR DESCRIPTION
**Pull request by Totktonada**
Fixes #27.

### CODE REVIEW

**Comment by Totktonada** [comment]
@dgreenru @ponomarevDmitri It would be glad if you will review this patch.

@isopov Ivan, can you please look into this PR too (cannot assign you as the reviewer).

File: src/main/java/org/tarantool/MsgPackLite.java [hunk 1]
```diff
@@ -91,6 +95,25 @@ public void pack(Object item, OutputStream os) throws IOException {
...
+                    if (isPositive && value.compareTo(BI_MAX_64BIT) > 0 ||
+                            value.compareTo(BI_MIN_LONG) < 0)
+                        throw new IllegalArgumentException(
+                            "Cannot encode BigInteger as MsgPack: out of -2^63..2^64-1 range");
+                    if (isPositive && value.compareTo(BI_MAX_LONG) > 0) {
+                        byte[] data = value.toByteArray();
+                        // data can contain leading zero bytes
+                        int offset = 0;
+                        while (offset < data.length && data[offset] == 0)
+                            ++offset;
```
Comment (ponomarevDmitri) [inline src/main/java/org/tarantool/MsgPackLite.java]: I've found that the assert and the preceding while-loop are redundant in the if-block. 
A condition of execution of the if-block is (at least): value.compareTo(BI_MAX_64BIT) <= 0 and value.compareTo(BI_MAX_LONG) > 0. Which guarantees that all bytes in the data[] will be zero starting from 0 position to {data.length - 9} position inclusively (in case when data.size() > 8).

File: src/test/java/org/tarantool/AbstractTarantoolConnectorIT.java [hunk 2]
```diff
@@ -180,27 +181,49 @@ protected TarantoolConnection openConnection() {
...
-            List parts = (List)key;
+            List parts = (List) key;
             for (int i = 0; i < parts.size(); i++) {
                 if (i != 0)
                     sb.append(", ");
                 Object k = parts.get(i);
-                if (k.getClass().isAssignableFrom(String.class)) {
+                if (k instanceof BigInteger) {
+                    appendBigInteger(sb, (BigInteger) k);
+                } else if (k.getClass().isAssignableFrom(String.class)) {
```
Comment (ponomarevDmitri) [inline src/test/java/org/tarantool/AbstractTarantoolConnectorIT.java]: Strange check that a class of variable 'k' must be an ancestor of String. Maybe it's better to use instanceof String in this case ( or instanceof CharSequece depending of what type of variable 'k' is supposed in code below)

**Comment by Totktonada** [comment]
NB: Filed #127 to cover msgpack-lite with unit tests.

File: src/main/java/org/tarantool/MsgPackLite.java (hunk 1 above)
Comment (Totktonada) [reply src/main/java/org/tarantool/MsgPackLite.java]: To be honest, I'm feel uncomfortable w/o actual checking that leading bytes are zero. But I had rewrote the code to split out loop with asserts from the main logic. Hope it'll look more clean.

File: src/test/java/org/tarantool/AbstractTarantoolConnectorIT.java (hunk 2 above)
Comment (Totktonada) [reply src/test/java/org/tarantool/AbstractTarantoolConnectorIT.java]: Yep, this check is strange one. I had replaced it with `instanceof String`.
